#  NumPy және Машиналық Оқыту үшін Python Негіздері

**Тапсырма саны:** 10  

##  Нұсқаулық

Төмендегі 10 тапсырманың әрқайсысында `# КОДТЫ ОСЫНДА ЖАЗ` деген белгі бар. Сол жерге өз шешімінді жаз.


In [ ]:
# Қажетті кітапханаларды импорттау
import numpy as np
import math

# I Бөлім: NumPy Кітапханасымен Жұмыс

**NumPy** (Numerical Python) сандық есептеулерге арналған Python кітапханасы. Ол көп өлшемді массивтермен (ndarray) жұмыс істеуге, математикалық операциялар жүргізуге және деректерді өңдеуге мүмкіндік береді. Машиналық оқытуда NumPy матрицалық есептеулер мен деректер алдын ала өңдеуінің негізі болып табылады.

> **Тапсырмалар 1–5:** NumPy массивтерін құру, индекстеу, операциялар және статистика.

## Тапсырма 1: NumPy Массивін Құру және Негізгі Сипаттамалар

**Мақсат:** NumPy массивін қолмен жасау және оның қасиеттерін зерттеу.

**Шарт:**

1. `[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]` мәндерінен тұратын NumPy массивін жаса.
2. Массивтің мынадай сипаттамаларын экранға шығар:
   - Өлшемі (`shape`)
   - Деректер типі (`dtype`)
   - Элементтер саны (`size`)
   - Өлшемдер саны (`ndim`)

**Күтілетін нәтиже үлгісі:**
```
Массив: [ 10  20  30  40  50  60  70  80  90 100]
Өлшемі: (10,)
Деректер типі: int64
Элементтер саны: 10
Өлшемдер саны: 1
```

In [2]:
# Тапсырма 1: NumPy массивін құру
import numpy as np
import math
a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(a.shape)
print(a.dtype)
print(a.size)
print(a.ndim)


(10,)
int64
10
1


## Тапсырма 2: Матрица Құру және Матрицалық Операциялар

**Мақсат:** 2D массив (матрица) жасау және негізгі матрицалық операцияларды орындау.

NumPy-да матрицалар 2 өлшемді ndarray ретінде сақталады. Машиналық оқытуда деректер жиыны көбінесе (n_samples × n_features) пішіндегі матрица түрінде ұсынылады. Матрицалық операциялар линейлі регрессия, нейрондық желілер және басқа алгоритмдердің негізін қалайды.

**Шарт:**

1. Мынадай 3×3 матрицаны жаса:
```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```
2. Осы матрицаны **транспонирлей** (`.T`).
3. Матрицаны өзіне **матрицалық көбейт** (`np.dot` немесе `@`).
4. Нәтижелерді экранға шығар.

In [4]:
# Тапсырма 2: Матрица және матрицалық операциялар
import numpy as np
import math
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
a = arr.T
r = np.dot(arr, a)
print(r)


[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


## Тапсырма 3: Индекстеу, Тілімдеу (Slicing) және Сүзгілеу

**Мақсат:** NumPy массивіндегі элементтерге индекс арқылы қол жеткізу және шарт бойынша сүзу.

NumPy-да Boolean маска — шартқа сай элементтерді таңдаудың тиімді тәсілі. Мысалы, деректерден аномалиялар немесе белгілі бір диапазондағы мәндерді жылдам алып тастауға болады. Бұл алдын ала өңдеу (preprocessing) кезеңінде жиі қолданылады.

**Шарт:**

1. 1-ден 20-ға дейінгі сандардан тұратын массив жаса (`np.arange`).
2. Массивтің **алғашқы 5** элементін шығар.
3. Массивтің **соңғы 5** элементін шығар.
4. Массивтің **жұп индекстегі** элементтерін шығар (0, 2, 4, ...).
5. Мәні **10-нан үлкен** элементтерді ғана шығар (Boolean индекстеу).

In [7]:
# Тапсырма 3: Индекстеу, тілімдеу және сүзгілеу

# КОДТЫ ОСЫНДА ЖАЗ

import numpy as np
st = 1
stop = 21
step = 1

arr = np.arange(st, stop, step)
print(arr[0:5])
print(arr[-5:])
print(arr[::2])
m = arr>10
print(arr[m])

[1 2 3 4 5]
[16 17 18 19 20]
[ 1  3  5  7  9 11 13 15 17 19]
[11 12 13 14 15 16 17 18 19 20]


## Тапсырма 4: Статистикалық Функциялар

**Мақсат:** NumPy-дың кірістірілген статистикалық функцияларын пайдалану.

Деректерді зерттеудің (EDA) бірінші қадамы — негізгі статистикалық көрсеткіштерді есептеу. Орташа мән, медиана, стандартты ауытқу және персентильдер деректер таралуын түсінуге көмектеседі. NumPy бұл есептеулерді векторланған түрде өте жылдам орындайды.

**Шарт:**

`np.random.seed(42)` арқылы кездейсоқтықты бекіт, содан кейін 0-ден 100-ге дейінгі **50 кездейсоқ бүтін сан** жаса.

Келесі статистикалық көрсеткіштерді есепте және шығар:
- Минимум және максимум
- Орташа мән (mean)
- Медиана
- Стандартты ауытқу
- Дисперсия
- 25-ші және 75-ші персентильдер

In [9]:
# Тапсырма 4: Статистикалық функциялар
np.random.seed(42)  # Қайталануы үшін кездейсоқтықты бекіту

# КОДТЫ ОСЫНДА ЖАЗ
a = np.random.randint(0, 101, size=50)

print(np.max(a))
print(np.min(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))

100
1
52.08
57.5
28.62016072631319
819.1136


## Тапсырма 5: Пішінді Өзгерту (Reshape) және Хабарлау (Broadcasting)

**Мақсат:** Массив пішінін өзгерту және NumPy broadcasting механизмін түсіну.

Broadcasting  NumPy-дың әртүрлі пішіндегі массивтерге автоматты түрде арифметикалық операция қолдану мүмкіндігі. Reshape функциясы деректерді нейрондық желілерге немесе sklearn модельдеріне беру алдында жиі қолданылады.

**Шарт:**

1. 1-ден 12-ге дейінгі сандардан тұратын массив жаса (`np.arange`).
2. Оны **3×4 матрицаға** түрлендір (`reshape`).
3. Матрицаның **әр жолына** `[10, 20, 30, 40]` векторын қос (broadcasting).
4. Матрицаның **әр бағанын** `[[1], [2], [3]]` бағандық векторына көбейт (broadcasting).
5. Нәтижелерді шығар.

In [15]:
# Тапсырма 5: Reshape және Broadcasting

# КОДТЫ ОСЫНДА ЖАЗ
import numpy as np
st = 1
stop = 13
step = 1

arr = np.arange(st, stop, step)
a = arr.reshape(3, 4)
row_vector = np.array([10, 20, 30, 40])
matrix_plus_row = a + row_vector
col_vector = np.array([[1], [2], [3]])
matrix_times_col = a * col_vector
print(matrix_times_col)

print(a)

[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# II Бөлім: Машиналық Оқыту үшін Python Негіздері

Python-ның функциялары мен кластары машиналық оқыту жүйелерін модульдік және қайта пайдалануға болатын түрде құруға мүмкіндік береді. ML pipeline-дарын, деректерді өңдеу логикасын және модель архитектурасын таза кодпен ұйымдастыру үшін OOP принциптері өте маңызды. scikit-learn кітапханасының өзі де осындай кластық құрылымға негізделген.

> **Тапсырмалар 6–10:** Функциялар, декораторлар, кластар және ML компоненттерін модельдеу.

## Тапсырма 6: ML Алдын Ала Өңдеу Функциялары

**Мақсат:** Деректерді нормализациялайтын және стандарттайтын функциялар жазу.

Нормализация мен стандарттау — ML алгоритмдерінің дұрыс жұмыс істеуі үшін маңызды алдын ала өңдеу қадамдары. Min-Max нормализациясы мәндерді [0, 1] диапазонына, Z-score стандарттауы орташа мәнді 0, стандартты ауытқуды 1 етіп түрлендіреді. Бұл SVM, KNN, нейрондық желі сияқты алгоритмдер үшін өте маңызды.

**Шарт:**

Екі функция жаз:

**`min_max_normalize(arr)`** — Min-Max нормализациясы:
$$x_{norm} = \frac{x - x_{min}}{x_{max} - x_{min}}$$

**`z_score_standardize(arr)`** — Z-score стандарттауы:
$$x_{std} = \frac{x - \mu}{\sigma}$$

Екі функцияны да `[2, 4, 4, 4, 5, 5, 7, 9]` массивіне қолдан және нәтижені шығар.

In [16]:
# Тапсырма 6: Нормализация және стандарттау функциялары
import numpy as np
# КОДТЫ ОСЫНДА ЖАЗ
arr = np.array([2, 4, 4, 4, 5, 5, 7, 9])
def min_max_normalize(arr):
  arr = np.array(arr, dtype=float)
  minn = np.min(arr)
  maxx = np.max(arr)
  return (arr-minn)/(maxx - minn)
def z_score_standardize(arr):
  arr = np.array(arr, dtype=float)
  mean = np.array(arr)
  std = np.std(arr)
  return (arr-mean)/std
print(min_max_normalize(arr))
print(z_score_standardize(arr))




[0.         0.28571429 0.28571429 0.28571429 0.42857143 0.42857143
 0.71428571 1.        ]
[0. 0. 0. 0. 0. 0. 0. 0.]


## Тапсырма 7: Рекурсия және Lambda Функциялар

**Мақсат:** Рекурсивті функция және lambda өрнектерін ML контекстінде қолдану.

Lambda функциялар — атаусыз шағын функциялар, ML-де деректерді трансформациялау үшін `map()`, `filter()`, `sorted()` функцияларымен жиі қолданылады. Рекурсия болса күрделі алгоритмдерді (мысалы, шешім ағашының тереңдігін есептеу) элегантты жазуға мүмкіндік береді.

**Шарт:**

1. **Рекурсивті функция:** `factorial(n)` — n! санын рекурсия арқылы есепте.
2. **Lambda:** `[0.1, 0.5, 0.9, 1.5, -0.3, 2.0]` тізімінен тек `[0, 1]` диапазонындағы мәндерді `filter` + `lambda` арқылы алып шығар.
3. **Lambda + map:** `[-2, -1, 0, 1, 2]` тізіміндегі әр элементке ReLU активация функциясын `map` + `lambda` арқылы қолдан.

> ReLU(x) = max(0, x)

In [ ]:
# Тапсырма 7: Рекурсия және Lambda функциялар

# КОДТЫ ОСЫНДА ЖАЗ
def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n-1)
n = [0.1, 0.5, 0.9, 1.5, -0.3, 2.0]
f = list(filter(lambda x: 0 <= x <= 1, n))
print(f)

v = [-2, -1, 0, 1, 2]
r = list(map(lambda x: max(0, x), v))
print(r)


## Тапсырма 8: Кластар — ML Метрикаларын Есептеуші

**Мақсат:** OOP принциптерін пайдаланып, классификация метрикаларын есептейтін класс жазу.

Машиналық оқытуда модель сапасын бағалау үшін Accuracy, Precision, Recall, F1-score метрикалары қолданылады. Оларды бір класс ішінде топтастыру кодтың модульдігін арттырады және sklearn-дің `classification_report` функциясына ұқсас нәтиже береді.

**Шарт:**

`ClassificationMetrics` атты класс жаз. Конструктор `y_true` (нақты мәндер) және `y_pred` (болжамдар) параметрлерін қабылдасын.

Класта мынадай әдістер болуы керек:
- `accuracy()` — дұрыс болжамдар үлесі
- `precision()` — дәлдік: TP / (TP + FP)
- `recall()` — толықтық: TP / (TP + FN)
- `f1_score()` — F1: 2 × (precision × recall) / (precision + recall)
- `report()` — барлық метрикаларды форматталған түрде шығарады

Тест деректері:
```python
y_true = [1, 0, 1, 1, 0, 1, 0, 0, 1, 0]
y_pred = [1, 0, 1, 0, 0, 1, 1, 0, 1, 0]
```

In [ ]:
# Тапсырма 8: ClassificationMetrics класы

# Тест деректері
y_true = [1, 0, 1, 1, 0, 1, 0, 0, 1, 0]  # Нақты белгілер
y_pred = [1, 0, 1, 0, 0, 1, 1, 0, 1, 0]  # Болжамдар

# КОДТЫ ОСЫНДА ЖАЗ


## Тапсырма 9: Мұрагерлік (Inheritance) — ML Модель Иерархиясы

**Мақсат:** Python-да кластар иерархиясын (мұрагерлік) пайдаланып ML модельдерін модельдеу.

Мұрагерлік (inheritance) — OOP-тың негізгі принципі. scikit-learn барлық модельдерін `BaseEstimator` базалық класынан туындатады, бұл `fit()`, `predict()`, `score()` сияқты ортақ интерфейсті қамтамасыз етеді. Осы паттернді түсіну ML кітапханаларының архитектурасын жобалауға негіз береді.

**Шарт:**

1. **`BaseModel`** — базалық класс:
   - `__init__(self, model_name)` — модель атын сақтайды
   - `fit(X, y)` — `NotImplementedError` шығарады (абстрактілі)
   - `predict(X)` — `NotImplementedError` шығарады (абстрактілі)
   - `describe()` — модель туралы ақпаратты шығарады

2. **`LinearRegressionModel(BaseModel)`** — туынды класс:
   - `fit(X, y)` — `np.linalg.lstsq` арқылы коэффициенттерді табады
   - `predict(X)` — `X @ weights` арқылы болжайды
   - `describe()` — базалық сипаттаманы + коэффициенттерді шығарады

3. Тест деректерінде `fit` → `predict` → `describe` тізбегін шақыр.

In [20]:
# Тапсырма 9: Мұрагерлік — ML Модель Иерархиясы

# Тест деректері


# КОДТЫ ОСЫНДА ЖАЗ

import numpy as np

class BaseModel:
    def __init__(self):
        pass
    def fit(self, X, y):
        raise NotImplementedError
    def predict(self, X):
        raise NotImplementedError

class RegressionModel(BaseModel):
    def __init__(self):
        super().__init__()
        self.coef_ = None
        self.intercept_ = None
    def fit(self, X, y):
        X_b = np.column_stack([np.ones(X.shape[0]), X])
        theta = np.linalg.pinv(X_b.T @ X_b) @ X_b.T @ y
        self.intercept_ = theta[0]
        self.coef_ = theta[1:]
    def predict(self, X):
        return X @ self.coef_ + self.intercept_

class ClassificationMetrics:
    def __init__(self, y_true, y_pred):
        self.y_true = y_true
        self.y_pred = y_pred
    def accuracy(self):
        return sum(t==p for t,p in zip(self.y_true,self.y_pred))/len(self.y_true)
    def precision(self):
        TP = sum((t==1 and p==1) for t,p in zip(self.y_true,self.y_pred))
        FP = sum((t==0 and p==1) for t,p in zip(self.y_true,self.y_pred))
        return TP/(TP+FP) if (TP+FP)>0 else 0
    def recall(self):
        TP = sum((t==1 and p==1) for t,p in zip(self.y_true,self.y_pred))
        FN = sum((t==1 and p==0) for t,p in zip(self.y_true,self.y_pred))
        return TP/(TP+FN) if (TP+FN)>0 else 0
    def f1_score(self):
        p = self.precision()
        r = self.recall()
        return 2*(p*r)/(p+r) if (p+r)>0 else 0
    def report(self):
        print(f"Accuracy : {self.accuracy():.3f}")
        print(f"Precision: {self.precision():.3f}")
        print(f"Recall   : {self.recall():.3f}")
        print(f"F1-score : {self.f1_score():.3f}")

x_train = np.column_stack([np.ones(20), np.random.randn(20)])
y_train = 3 * x_train[:,1] + 5 + np.random.randn(20)*0.5
reg = RegressionModel()
reg.fit(x_train[:,1].reshape(-1,1), y_train)
y_pred = reg.predict(x_train[:,1].reshape(-1,1))
y_true = (y_train > np.median(y_train)).astype(int)
y_pred_class = (y_pred > np.median(y_pred)).astype(int)
metrics = ClassificationMetrics(y_true, y_pred_class)
metrics.report()
x_train = np.column_stack([np.ones(20), np.random.randn(20)])  # Бір фичалы деректер
y_train = 3 * x_train[:, 1] + 5 + np.random.randn(20) * 0.5  # y = 3x + 5 + шу
metrics = ClassificationMetrics(y_true, y_pred)
metrics.report()



Accuracy : 1.000
Precision: 1.000
Recall   : 1.000
F1-score : 1.000
Accuracy : 0.000
Precision: 0.000
Recall   : 0.000
F1-score : 0.000


## !КҮРДЕЛІ
##Тапсырма 10: Толыққанды ML Pipeline Класы

**Мақсат:** Нақты ML жүйесін модельдейтін толыққанды Pipeline класын жазу.

ML Pipeline  деректерді алдын ала өңдеу, модельді оқыту және бағалау қадамдарын автоматты реттілікпен орындайтын құрылым. sklearn-дің `Pipeline` класы осындай принципте жұмыс істейді. Мұны өз бетімен жүзеге асыру бүкіл ML жұмыс ағынын терең түсінуге мүмкіндік береді.

**Шарт:**

`MLPipeline` класы жаз, ол мынадай кезең-кезеңді іске асырсын:

1. **`load_data(X, y)`** — деректерді сақтайды
2. **`train_test_split(test_ratio=0.2)`** — деректерді оқыту/тест жиынтықтарына бөледі
3. **`normalize()`** — оқыту жиынтығы бойынша Min-Max нормализациясын жасайды (тест жиынына да қолданады)
4. **`train()`** — `np.linalg.lstsq` арқылы линейлі регрессия оқытады
5. **`evaluate()`** — MSE және R² метрикаларын есептейді
6. **`run()`** — барлық қадамдарды дұрыс ретпен шақырады

Тест деректерінде толық `run()` жүргіз және нәтижені шығар.

> **Кеңес:** R² = 1 - SS_res / SS_tot, мұндағы SS_res = Σ(y - ŷ)², SS_tot = Σ(y - ȳ)²

In [21]:
# Тапсырма 10: Толыққанды ML Pipeline класы

# Тест деректері
np.random.seed(42)
n_samples = 100
X_data = np.random.randn(n_samples, 3)  # 100 үлгі, 3 белгі
y_data = 2 * X_data[:, 0] - 1.5 * X_data[:, 1] + 0.5 * X_data[:, 2] + np.random.randn(n_samples) * 0.3

# КОДТЫ ОСЫНДА ЖАЗ
import numpy as np

class MLPipeline:
    def __init__(self):
        self.X = None
        self.y = None
        self.X_train = None
        self.X_test = None
        self.y_train = None
        self.y_test = None
        self.X_min = None
        self.X_max = None
        self.coef_ = None
        self.intercept_ = None

    def load_data(self, X, y):
        self.X = np.array(X, dtype=float)
        self.y = np.array(y, dtype=float)

    def train_test_split(self, test_ratio=0.2):
        n = self.X.shape[0]
        idx = np.arange(n)
        np.random.shuffle(idx)
        split = int(n*(1-test_ratio))
        train_idx, test_idx = idx[:split], idx[split:]
        self.X_train = self.X[train_idx]
        self.X_test = self.X[test_idx]
        self.y_train = self.y[train_idx]
        self.y_test = self.y[test_idx]

    def normalize(self):
        self.X_min = self.X_train.min(axis=0)
        self.X_max = self.X_train.max(axis=0)
        self.X_train = (self.X_train - self.X_min) / (self.X_max - self.X_min)
        self.X_test = (self.X_test - self.X_min) / (self.X_max - self.X_min)

    def train(self):
        X_b = np.column_stack([np.ones(self.X_train.shape[0]), self.X_train])
        theta, _, _, _ = np.linalg.lstsq(X_b, self.y_train, rcond=None)
        self.intercept_ = theta[0]
        self.coef_ = theta[1:]

    def evaluate(self):
        y_pred = self.predict(self.X_test)
        mse = np.mean((self.y_test - y_pred)**2)
        ss_tot = np.sum((self.y_test - np.mean(self.y_test))**2)
        r2 = 1 - np.sum((self.y_test - y_pred)**2)/ss_tot
        print(f"MSE: {mse:.3f}, R²: {r2:.3f}")

    def predict(self, X):
        return X @ self.coef_ + self.intercept_

    def run(self, X, y, test_ratio=0.2):
        self.load_data(X, y)
        self.train_test_split(test_ratio)
        self.normalize()
        self.train()
        self.evaluate()


np.random.seed(42)
X = np.random.rand(50, 2)*10
y = 3*X[:,0] - 2*X[:,1] + 5 + np.random.randn(50)*0.5

pipeline = MLPipeline()
pipeline.run(X, y)


MSE: 0.204, R²: 0.998


# Қорытынды және Өзін-өзі Бағалау

(міндетті емес) Барлық тапсырмаларды орындап болған соң, төмендегі кестені толтыр:

| Тапсырма | Тақырып | Орындалды? | Қиындықтар |
|:--------:|---------|:----------:|------------|
| 1 | NumPy массиві және сипаттамалар | ☐ | |
| 2 | Матрица және матрицалық операциялар | ☐ | |
| 3 | Индекстеу және сүзгілеу | ☐ | |
| 4 | Статистикалық функциялар | ☐ | |
| 5 | Reshape және Broadcasting | ☐ | |
| 6 | Нормализация функциялары | ☐ | |
| 7 | Рекурсия және Lambda | ☐ | |
| 8 | ClassificationMetrics класы | ☐ | |
| 9 | Мұрагерлік — ML иерархиясы | ☐ | |
| 10 | ML Pipeline класы | ☐ | |

---

**Пікір (міндетті емес):**

_Осы үй жұмысын орындау барысында не үйрендің? Қандай тапсырма ең қызықты болды?_


---